### ISSUE TITLE
Wrong number of arguments: eq, 1

### ISSUE THREAD

**Issue by galeo** [Lindydancer/lisp-extra-font-lock#4]
https://github.com/Lindydancer/lisp-extra-font-lock/blob/092f5a6e75ddfc8051b252f10e182723a17980e4/lisp-extra-font-lock.el#L507

Blame to this commit 77d153a54c20f90064076f3f4ff4ef0e44d1c2bf.

**Comment by Lindydancer** [comment]
Thanks!

I see the problem -- I'll make a new release as soon as possible, hopefully
tonight!

    -- Anders

**Comment by Lindydancer** [comment]
I just pushed a new version with a fix, could you give it a try?

    -- Anders

**Comment by galeo** [comment]
It's fixed now. Thanks!

**Comment by Lindydancer** [comment]
Thanks for reporting this!
